### ISSUE TITLE
Cannot import Taxjar using TypeScript

### ISSUE THREAD

**Issue by zgosalvez** [taxjar/taxjar-node#13]
This used to work on v1, now it throws an error on v2.

```typescript
import * as taxjar from 'taxjar';
```

```bash
Module '"/node_modules/taxjar/dist/taxjar"' resolves to a non-module entity and cannot be imported using this construct.
```

Attempting to import as documented throws a different error.

```ts
import Taxjar from 'taxjar';
```

```sh
Module '"/node_modules/taxjar/dist/taxjar"' has no default export.
```

Here's my `tsconfig.json` file.

```json
{
  "compilerOptions": {
    "lib": ["es2017"],
    "module": "commonjs",
    "noImplicitReturns": true,
    "outDir": "lib",
    "sourceMap": true,
    "target": "es6"
  },
  "compileOnSave": true,
  "include": [
    "src"
  ],
  "strictNullChecks": true
}
```

**Comment by fastdivision** [comment]
@zgosalvez This looks like an ES6 / CommonJS interop issue since we're now using TypeScript on our end to compile the package. Can you pass [esModuleInterop](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html) in your `tsconfig.json`?

```json
{
  "compilerOptions": {
    "lib": ["es2017"],
    "module": "commonjs",
    "noImplicitReturns": true,
    "outDir": "lib",
    "sourceMap": true,
    "target": "es6",
    "esModuleInterop": true
  },
  "compileOnSave": true,
  "include": [
    "src"
  ],
  "strictNullChecks": true
}
```

Afterwards, go ahead and use:

```javascript
import Taxjar from 'taxjar';
```

**Comment by fastdivision** [comment]
Updated the README authentication example to address this issue.

**Comment by zgosalvez** [comment]
Thanks, @fastdivision . That did it, tho I had to modify how I imported other dependencies.

**Comment by eboswort** [comment]
Is there a fix for this that doesn't require `esModuleInterop`? That creates a bunch of other issues in the app I'm working on.

**Comment by brannondorsey** [comment]
> Is there a fix for this that doesn't require esModuleInterop? That creates a bunch of other issues in the app I'm working on.

We'd like to use this module, however we aren't in a position to refactor the rest of our imports to use the `esModuleInterop` compiler flag. Is there another way to use this module?
