### ISSUE TITLE
Cannot find type definition file for 'bluebird'

### ISSUE THREAD

**Issue by zgosalvez** [taxjar/taxjar-node#17]
Just updated to taxjar 2.1.1, but running `tsc` now produces this error:

```sh
node_modules/taxjar/dist/taxjar.d.ts(1,23): error TS2688: Cannot find type definition file for 'bluebird'.
```

**Comment by fastdivision** [comment]
@zgosalvez Sorry about that, I just included the necessary types under `dependencies` in package.json. Try updating to v2.1.2. Thank you!
