### ISSUE TITLE
Replace Bluebird with Native ES6 Promises

### ISSUE THREAD

**Issue by jake-lambert-volusion** [taxjar/taxjar-node#21]
Bluebird is a very large dependency. Is there some reason your are not just using native Promises?

**Comment by fastdivision** [comment]
I'd be open to using native promises in the near future to reduce our [bundle size](https://bundlephobia.com/result?p=taxjar@2.2.0). I don't see a specific reason preventing us from doing so at this time given our Node v4.0+ requirement. Thanks for the feedback @jake-lambert-volusion, we'll look into this soon!
