### ISSUE TITLE
Not Acceptable Shipment is missing .NET API

### ISSUE THREAD

**Issue by exodmn** [taxjar/taxjar-node#28]
Similar to issue #14 , I am trying the example from the documentation, but I keep getting the Not Acceptable Shipment is missing error. I am using the .Net api and I am passing a JSON with the specified values. I also saw in issue #18 that it was mentioned that the user needed to pass a different object type. Does the .net API expect a JSON or some other object type? Based on the samples I was assuming it was a JSON. 

Any help would be greatly appreciated.

**Comment by exodmn** [comment]
Figured out the issue

**Comment by bhushan90** [comment]
@exodmn  could yo please tell me the solution for that problem

**Comment by ScottRudiger** [comment]
@bhushan90, which API client are you using? [.NET](https://github.com/taxjar/taxjar.net) as well? And what's your input to the `TaxForOrder` method—same as the example?
