### ISSUE TITLE
Access blocked by CORS Policy

### ISSUE THREAD

**Issue by tbonz** [taxjar/taxjar-node#31]
Trying to use the sales tax api and my requests are failing due to No 'Access-Control-Allow-Origin' header is present on the requested resource.

<img width="1155" alt="Screen Shot 2019-06-04 at 10 35 59 AM" src="https://user-images.githubusercontent.com/1107725/58895099-d0ff2f80-86b8-11e9-9009-929a16b0afc8.png">
<img width="1156" alt="Screen Shot 2019-06-04 at 10 34 19 AM" src="https://user-images.githubusercontent.com/1107725/58895112-d78da700-86b8-11e9-8639-bf631e416824.png">

**Comment by ScottRudiger** [comment]
@tbonz TaxJar doesn't support AJAX / CORS. This is so API tokens won't be exposed in a frontend request. You can use `taxjar` by either making requests from a backend or through a proxy.

**Comment by tbonz** [comment]
Thanks for the quick reply!  I will proxy the request like you mentioned.
