### ISSUE TITLE
No Changelog/History

### ISSUE THREAD

**Issue by seriallos** [taxjar/taxjar-node#37]
I can't find a changelog or release notes for any versions of this library so it's difficult to verify additions/changes to the library when updating my deps. The only thing I can find at all are API notes on the TaxJar website but those are labelled by date and don't correspond to this library's version scheme.

I'm guessing there are no compatibility changes but it's nice to be able to have a version history available.

**Comment by ScottRudiger** [comment]
@seriallos Thanks for the request! It's in our backlog and we plan to add a changelog specific to the API client soon. In the meantime, for anyone else who happens to come across this you can view the API changelog [here](https://developers.taxjar.com/api/reference/?shell#changelog).
