### ISSUE TITLE
Return types

### ISSUE THREAD

**Issue by mixedCase** [taxjar/taxjar-node#38]
Currently all methods return `any`, meaning we have to define your backend's responses on our end (with our own checks to make sure our documentation-based assumptions are actually correct) to have type-safety. Any plans to support this?

**Comment by ScottRudiger** [comment]
@mixedCase Thanks for bringing this up! Yes, actually we plan to add return types for all the methods. We'll likely use a union type and return either that type or an error type.

Will update you here when it's released. 👍
