### ISSUE TITLE
TaxJar error

### ISSUE THREAD

**Issue by jssuttles** [taxjar/taxjar-node#5]
TaxJar errors come back as JSON.
ex: {
 error: "BadRequest",
 detail: "...",
 status: 400
}
These do not get rejected in /lib/util/request.js.
line 23-27:
if (result instanceof Error) {
defer.reject(result);
} else {
defer.resolve(result);
}
Does not work since the JSON is not an instance of Error.

**Comment by fastdivision** [comment]
@jssuttles Thanks, just fixed this in 1.4.0!
