### ISSUE TITLE
Incorrect type for TaxForOrderRes.tax.jurisdictions

### ISSUE THREAD

**Issue by brannondorsey** [taxjar/taxjar-node#58]
According to the Taxjar [API docs](https://developers.taxjar.com/api/reference/#post-calculate-sales-tax-for-an-order), the POST `/v2/taxes` endpoint returns a `tax` object with `jurisdictions` property which contains an object with key, value pairs.

<img width="456" alt="Screen Shot 2021-01-25 at 2 26 22 PM" src="https://user-images.githubusercontent.com/3193533/105755522-66e46f80-5f19-11eb-8fff-0104e185c039.png">

<img width="292" alt="Screen Shot 2021-01-25 at 2 26 28 PM" src="https://user-images.githubusercontent.com/3193533/105755541-6ba92380-5f19-11eb-84c3-d58810377a3d.png">

However, the `TaxForOrderRes.tax.jurisdictions` type definition in this module contradicts the API docs (and the live results in my experience) [by declaring this value contains an array of jurisdiction objects](https://github.com/taxjar/taxjar-node/blob/40e7974e556152725515a64f89ac064cf6a2a937/lib/types/returnTypes.ts#L22-L27).

<img width="312" alt="Screen Shot 2021-01-25 at 2 30 52 PM" src="https://user-images.githubusercontent.com/3193533/105755930-f558f100-5f19-11eb-980e-7444e6eef319.png">

Is this type definition wrong? Should the `[]` at the end of the type deceleration by omitted?

**Comment by fastdivision** [comment]
@brannondorsey Good catch, this should be an object and not an array. Removed `[]`.
